# Proyecto para ejercicios sobre TADs

# Sesión TAD Lista memoria dispersa (punteros)

sesionL2: pruebaLista.c lista.o
	gcc -g pruebaLista.c lista.o -o sesionL2

lista.o: lista.c lista.h
	gcc -g -c lista.c

limpiar:
	rm *.o

